---
abstract: 'Generate markup and code for jQuery JavaScript framework'
author:
  - 'David P.C. Wollmann <converter42 at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaScript-Framework-jQuery
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  JSON: 2.12
  Moose: 0.77
  MooseX::Params::Validate: 0.09
  MooseX::Types: 0.10
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0.14
  perl: 5.8.0.000
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
